### ISSUE TITLE
Tolerate missing name, version fields?

### ISSUE THREAD

**Issue by callumlocke** [HenrikJoreteg/fixpack#10]
Currently fixpack errors out if you don't have "name" and "version" properties.

Couldn't it just print a warning (and then proceed to ocd-ify the file as usual)?

These fields are only required for publishing on npm, not for private apps. Commands like `npm install --save foo` work fine without them, and services like Heroku don't care about them. In fact fixpack is the first thing I have encountered that insists on them.

**Comment by HenrikJoreteg** [comment]
this is now configurable, see new readme

**Comment by callumlocke** [comment]
nice solution :+1:
