### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by HansHammel** [HenrikJoreteg/fixpack#24]

**Comment by slang800** [comment]
I added tests in my fork, but it's a pretty significant rewrite https://github.com/slang800/fixpack/blob/master/test/index.coffee

**Comment by HansHammel** [comment]
Nice. One thing: Pay attention to the spdx-correct package it might correct things like LMIT -> MIT while this might be some sort of proprietary license. I came across this recently.

**Comment by HenrikJoreteg** [comment]
Closing due to age... 

🤷‍♂ this was a total quick hack project ages ago. Happy to take a PR and add collaborators who want to add tests.
