### ISSUE TITLE
Let's move 'scripts' to the top.

### ISSUE THREAD

**Issue by NodeGuy** [HenrikJoreteg/fixpack#25]
The first thing I check when reading someone else's `package.json` file is the `scripts` field so that I know how to interact with it.  Let's include `scripts` as one of the fields moved near the top to facilitate this.

**Comment by slang800** [comment]
I don't think that's very common. Most of the time, I'm looking for where to report bugs, what a package depends upon (when I'm looking for out-of-date or excessive deps), and who wrote it. I think those are the post important fields, based on what sites like npms.io and npmjs.com show. Plus, you could always avoid opening the file altogether and just use `jq '.scripts' < ./package.json`.
