### ISSUE TITLE
Return non-zero exit code for warnings.

### ISSUE THREAD

**Issue by NodeGuy** [HenrikJoreteg/fixpack#26]
I'd like to use this tool as a mandatory step in my CI server and have integration fail if, e.g., fields are missing.

Today the tool reports `missing description` for my `package.json` but returns `0` as the exit code.

**Comment by jdxcode** [comment]
If it's a warning it shouldn't exit with non-zero. It would probably be better to check the output contains any stderr output

**Comment by make-github-pseudonymous-again** [comment]
@NodeGuy You can also configure `fixpack` in `.fixpackrc` to treat missing `description` as an error instead of a warning.

**Comment by NodeGuy** [comment]
Thank you.
